# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
 

jobs:

    
  Installing_node_js:
      runs-on: ubuntu-latest
      steps:
       - name: checkout-action
         uses: actions/checkout@v3
       - name: install_nodejs
         run: |
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
              sudo apt-get install nodejs
              node --version
              npm --version
  Installing_pm2:
     needs: Installing_node_js
     runs-on: ubuntu-latest
     steps: 
       - name: checkout-action
         uses: actions/checkout@v3
       - name: install_pm2
         run: |
              sudo npm i -g pm2
              echo "verify install pm2"
              pm2 --version
              pm2 start index.js
              ip
              
  
       
  deploy:
    needs: [Installing_node_js, Installing_pm2]
    runs-on: ubuntu-latest
    steps:
     - name: checkout-action
       uses: actions/checkout@v3
     - name: message
       run: |
            echo "verify install pm2"
            pm2 --version
            cd ~
            
            cd /home/runner/work/node_project/node_project
            pm2 start index.js
           
            
    
      
