name: Node.js Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run application
      
        run: |
          output $(node index.js)
          echo "$output"
       # run: echo "run application"


     
