# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

  Installing_pm2:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PM2
        run: |
          sudo npm install -g pm2
          which pm2
          pm2 --version

  deploy:
    needs: [build, Installing_pm2]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Verify PM2 installation
        run: |
            sudo npm install -g pm2
            pm2 --version || true 
      - name: Start application with PM2
        run: |
           pwd
           cd /home/ubuntu/actions-runner/_work/node_project/node_project
           pm2 stop index.js
           pm2 start index.js
           pm2 logs
